//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.23 at 02:50:52 PM EAT 
//


package com.zurion.soapservice.interfaces;


import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Contact complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Contact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maskedName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maskedPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hashedPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contact", propOrder = {
        "id",
        "fullName",
        "phoneNumber",
        "email",
        "idNumber",
        "dateOfBirth",
        "gender",
        "organization",
        "maskedName",
        "maskedPhoneNumber",
        "hashedPhoneNumber"
})
public class Contact {

    protected long id;
    @XmlElement(required = true)
    protected String fullName;
    @XmlElement(required = true)
    protected String phoneNumber;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String idNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfBirth;
    @XmlElement(required = true)
    protected String gender;
    @XmlElement(required = true)
    protected String organization;
    @XmlElement(required = true)
    protected String maskedName;
    @XmlElement(required = true)
    protected String maskedPhoneNumber;
    @XmlElement(required = true)
    protected String hashedPhoneNumber;

    /**
     * Gets the value of the id property.
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the fullName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the idNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * Sets the value of the idNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIdNumber(String value) {
        this.idNumber = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the gender property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the organization property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrganization(String value) {
        this.organization = value;
    }

    /**
     * Gets the value of the maskedName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaskedName() {
        return maskedName;
    }

    /**
     * Sets the value of the maskedName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaskedName(String value) {
        this.maskedName = value;
    }

    /**
     * Gets the value of the maskedPhoneNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaskedPhoneNumber() {
        return maskedPhoneNumber;
    }

    /**
     * Sets the value of the maskedPhoneNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaskedPhoneNumber(String value) {
        this.maskedPhoneNumber = value;
    }

    /**
     * Gets the value of the hashedPhoneNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHashedPhoneNumber() {
        return hashedPhoneNumber;
    }

    /**
     * Sets the value of the hashedPhoneNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHashedPhoneNumber(String value) {
        this.hashedPhoneNumber = value;
    }

}
